services:
  mongodb:
    image: mongodb:v1 #--name mongodb
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have created network manually using docker network command